services:
  - type: web
    name: vittavento-article
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        value: your_secret_key_here
    postDeployCommand: flask db upgrade
