"""Добавлена модель Article

Revision ID: 321441e37eaa
Revises: 60405ea2c1c2
Create Date: 2025-05-08 17:03:21.290143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '321441e37eaa'
down_revision = '60405ea2c1c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article')
    # ### end Alembic commands ###
