"""Initial

Revision ID: 60405ea2c1c2
Revises: 
Create Date: 2025-05-08 01:18:00.490129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60405ea2c1c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('view',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('view')
    # ### end Alembic commands ###
