"""Добавлена модель Color

Revision ID: e5499c614192
Revises: 4f64781daebb
Create Date: 2025-05-22 00:04:53.978298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5499c614192'
down_revision = '4f64781daebb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('color',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('model', schema=None) as batch_op:
        batch_op.drop_constraint('uix_model_code', type_='unique')
        batch_op.create_unique_constraint('uix_view_category_model_code', ['view_id', 'category_id', 'code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model', schema=None) as batch_op:
        batch_op.drop_constraint('uix_view_category_model_code', type_='unique')
        batch_op.create_unique_constraint('uix_model_code', ['view_id', 'category_id', 'code'])

    op.drop_table('color')
    # ### end Alembic commands ###
