"""Добавлено поле level в модель Article

Revision ID: ec4b7fbc6f5f
Revises: 16bbc19111b4
Create Date: 2025-05-25 20:32:26.419061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec4b7fbc6f5f'
down_revision = '16bbc19111b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.String(length=1), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('level')

    # ### end Alembic commands ###
